name: CI-CD Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # v3 -> v4 Upgrade!

      - name: Echo user login
        run: echo "Hello, ${{ github.actor }}"

  test:
    runs-on: ubuntu-latest
    name: Cypress Test Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # v3 -> v4 Upgrade!

      - name: Cypress run
        uses: cypress-io/github-action@v6 # Her şeyi (Node, Install, Run) bu halleder!
        with:
          record: true
          browser: chrome
        env:
          # key i GitHub Secrets'tan çekiyoruz.
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

        # PERFORMANS TESTLERİNİ EKLEDİK:
      - name: Run Artillery Performance Tests
        run: |
          cd Performance_Artillery
          npm install -g artillery
          artillery run your_test_file.yml

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4 # v3 -> v4 CRITICAL FIX!
        with:
          name: cypress-video
          path: cypress/videos/**/*.mp4
          retention-days: 1

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4 # v3 -> v4 CRITICAL FIX!
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*.png
          retention-days: 1
