name: CI-CD Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # v3 -> v4 Upgrade!

      - name: Echo user login
        run: echo "Hello, ${{ github.actor }}"

  test:
    runs-on: ubuntu-latest
    name: Cypress Test Job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # v3 -> v4 Upgrade!

      - name: Cypress run
        uses: cypress-io/github-action@v6 # Her şeyi (Node, Install, Run) bu halleder!
        with:
          record: true
          browser: chrome
        env:
          # key i GitHub Secrets'tan çekiyoruz.
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          MAILBOXLAYER_API_KEY: ${{ secrets.MAILBOXLAYER_API_KEY }}
          API_URL_MAILBOX: ${{ secrets.API_URL_MAILBOX }}

        # PERFORMANS TESTLERİNİ EKLEDİK:
      - name: Run Artillery Performance Tests
        if: always() # Performans testlerini her zaman çalıştır, Cypress testleri başarısız olsa bile.
        run: |
          cd Performance_Artillery
          echo "Current Directory: $(pwd)"
          echo "Files in this folder:"
          ls -R  # Klasörün içindekileri bize listele ki görelim!

          npm install -g artillery

          # SENIOR TRICK: Klasördeki tüm .yml ve .yaml file'larını döngü ile çalıştırarak tek seferde tüm performans testlerini gerçekleştirelim!
          for file in *{.yml,.yaml}; do
            [ -e "$file" ] || continue # Eğer dosya yoksa döngüden çık, hata basma
            echo "Running performance test for: $file"
            artillery run "$file"
          done

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4 # v3 -> v4 CRITICAL FIX!
        with:
          name: cypress-video
          path: cypress/videos/**/*.mp4
          retention-days: 1

      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4 # v3 -> v4 CRITICAL FIX!
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*.png
          retention-days: 1
